[package]
name        = "amadeus"
version     = "0.6.4"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"

[dependencies]
rand          = "0.7.3"
chrono        = "0.4.11"
typemap       = "0.3.3"
rust-ini      = "0.15.3"
argparse      = "0.2.2"
log           = "0.4.8"
env_logger    = "0.7.1"
curl          = "0.4.29"
regex         = "1.3.9"
serde         = "1.0.112"
serde_derive  = "1.0.112"
serde_json    = "1.0.55"
lazy_static   = "1.4.0"
markov        = "1.0.3"
ucd           = "0.1.1"
comfy-table   = "0.1.1"
unicase       = "2.6.0"

reqwest = { version = "0.10.6", features = ["json"] }
ical    = { version = "0.6.0", features = ["ical"] }
uuid    = { version = "0.8.1", features = ["serde"] }

[dependencies.serenity]
default-features = false
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"]
version = "0.8.6"
