[package]
name        = "amadeus"
version     = "2.1.9"
authors     = [ "Qeenon" ]
repository  = "https://github.com/Qeenon/Amadeus"
readme      = "README.md"
keywords    = [ "discord", "bot" ]
edition     = "2018"
description = "memory storage and artificial intelligence system"

[dependencies]
rand          = "0.7.3"
chrono        = "0.4.13"
typemap       = "0.3.3"
rust-ini      = "0.15.3"
argparse      = "0.2.2"
log           = "0.4.8"
env_logger    = "0.7.1"
curl          = "0.4.30"
regex         = "1.3.9"
serde         = "1.0.114"
serde_derive  = "1.0.114"
serde_json    = "1.0.56"
lazy_static   = "1.4.0"
markov        = "1.0.3"
ucd           = "0.1.1"
comfy-table   = "1.0.0"
futures-util  = "0.3.5"
qrcode        = "0.12.0"
cannyls       = "0.9.4"
bincode       = "1.3.1"

reqwest = { version = "0.10.6", features = ["json", "blocking"] }
ical    = { version = "0.6.0",  features = ["ical"] }
uuid    = { version = "0.8.1",  features = ["serde"] }

[dependencies.tokio]
version = "0.2.21"
features = ["full", "blocking", "sync"]

[dependencies.serenity]
default-features = false
git = "https://github.com/acdenisSK/serenity"
branch = "await_next"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"]
